### ISSUE TITLE
Does not output an image

### ISSUE THREAD

**Issue by marchellodev** [jdah/tetris-os#2]
The image builds and runs fine. After running, I can hear the audio playing, but it just displays "TETRIS TIME" (I have attached the screenshot below). Specifying `-monitor vc` did not help.

<details>
  <summary>Shell</summary>
  
```shell
mark@pop-os:~/Documents/Playgrodund/tetris-os$ make iso
i386-elf-ld -o ./bin/bootsect.bin src/stage0.o -Ttext 0x7C00 --oformat=binary
i386-elf-ld -o ./bin/kernel.bin src/keyboard.o src/music.o src/irq.o src/screen.o src/isr.o src/system.o src/math.o src/fpu.o src/font.o src/main.o src/idt.o src/sound.o src/timer.o src/speaker.o src/start.o  -Tsrc/link.ld
dd if=/dev/zero of=boot.iso bs=512 count=2880
2880+0 records in
2880+0 records out
1474560 bytes (1.5 MB, 1.4 MiB) copied, 0.0112492 s, 131 MB/s
dd if=./bin/bootsect.bin of=boot.iso conv=notrunc bs=512 seek=0 count=1
1+0 records in
1+0 records out
512 bytes copied, 5.4803e-05 s, 9.3 MB/s
dd if=./bin/kernel.bin of=boot.iso conv=notrunc bs=512 seek=1 count=2048
72+1 records in
72+1 records out
37152 bytes (37 kB, 36 KiB) copied, 0.000174547 s, 213 MB/s
mark@pop-os:~/Documents/Playgrodund/tetris-os$ qemu-system-i386 -drive format=raw,file=boot.iso -d cpu_reset -monitor stdio -device sb16 -audiodev pa,id=pulseaudio,out.frequency=48000,out.channels=2,out.format=s32
QEMU 4.2.1 monitor - type 'help' for more information
(qemu) CPU Reset (CPU 0)
EAX=00000000 EBX=00000000 ECX=00000000 EDX=00000000
ESI=00000000 EDI=00000000 EBP=00000000 ESP=00000000
EIP=00000000 EFL=00000000 [-------] CPL=0 II=0 A20=0 SMM=0 HLT=0
ES =0000 00000000 00000000 00000000
CS =0000 00000000 00000000 00000000
SS =0000 00000000 00000000 00000000
DS =0000 00000000 00000000 00000000
FS =0000 00000000 00000000 00000000
GS =0000 00000000 00000000 00000000
LDT=0000 00000000 00000000 00000000
TR =0000 00000000 00000000 00000000
GDT=     00000000 00000000
IDT=     00000000 00000000
CR0=00000000 CR2=00000000 CR3=00000000 CR4=00000000
DR0=00000000 DR1=00000000 DR2=00000000 DR3=00000000 
DR6=00000000 DR7=00000000
CCS=00000000 CCD=00000000 CCO=DYNAMIC 
EFER=0000000000000000
FCW=0000 FSW=0000 [ST=0] FTW=ff MXCSR=00000000
FPR0=0000000000000000 0000 FPR1=0000000000000000 0000
FPR2=0000000000000000 0000 FPR3=0000000000000000 0000
FPR4=0000000000000000 0000 FPR5=0000000000000000 0000
FPR6=0000000000000000 0000 FPR7=0000000000000000 0000
XMM00=00000000000000000000000000000000 XMM01=00000000000000000000000000000000
XMM02=00000000000000000000000000000000 XMM03=00000000000000000000000000000000
XMM04=00000000000000000000000000000000 XMM05=00000000000000000000000000000000
XMM06=00000000000000000000000000000000 XMM07=00000000000000000000000000000000
audio: Device sb16: audiodev default parameter is deprecated, please specify audiodev=pulseaudio
CPU Reset (CPU 0)
EAX=00000000 EBX=00000000 ECX=00000000 EDX=00000663
ESI=00000000 EDI=00000000 EBP=00000000 ESP=00000000
EIP=0000fff0 EFL=00000002 [-------] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0000 00000000 0000ffff 00009300
CS =f000 ffff0000 0000ffff 00009b00
SS =0000 00000000 0000ffff 00009300
DS =0000 00000000 0000ffff 00009300
FS =0000 00000000 0000ffff 00009300
GS =0000 00000000 0000ffff 00009300
LDT=0000 00000000 0000ffff 00008200
TR =0000 00000000 0000ffff 00008b00
GDT=     00000000 0000ffff
IDT=     00000000 0000ffff
CR0=60000010 CR2=00000000 CR3=00000000 CR4=00000000
DR0=00000000 DR1=00000000 DR2=00000000 DR3=00000000 
DR6=ffff0ff0 DR7=00000400
CCS=00000000 CCD=00000000 CCO=DYNAMIC 
EFER=0000000000000000
FCW=037f FSW=0000 [ST=0] FTW=00 MXCSR=00001f80
FPR0=0000000000000000 0000 FPR1=0000000000000000 0000
FPR2=0000000000000000 0000 FPR3=0000000000000000 0000
FPR4=0000000000000000 0000 FPR5=0000000000000000 0000
FPR6=0000000000000000 0000 FPR7=0000000000000000 0000
XMM00=00000000000000000000000000000000 XMM01=00000000000000000000000000000000
XMM02=00000000000000000000000000000000 XMM03=00000000000000000000000000000000
XMM04=00000000000000000000000000000000 XMM05=00000000000000000000000000000000
XMM06=00000000000000000000000000000000 XMM07=00000000000000000000000000000000


```
</details>

![image](https://user-images.githubusercontent.com/61112084/115266383-d648b480-a140-11eb-9a68-f150ae8d26b3.png)

**Comment by dtomvan** [comment]
same

**Comment by FlashDaggerX** [comment]
`qemu-system-i386` has the ability to its video output to a VNC server. On Unix-like systems, you can install a VNC client (such as `vncviewer`) to view the window.

On Unix-like systems:
* Start the emulator as specified in the `README`, but specify a VNC display at the end: 
```shell
$ qemu-system-i386 -drive format=raw,file=boot.iso -d cpu_reset -monitor stdio -device sb16 -audiodev alsa,id=coreaudio,out.frequency=48000,out.channels=2,out.format=s32 -vnc <:DISPLAY#>
```
* Connect to the display using `vncviewer` (or some alternative):
```shell
$ vncviewer <:DISPLAY#>
```
* ??? Profit? https://i.imgur.com/YGSHqG1.mp4

**Comment by farmerbb** [comment]
I had to compile using @parkerlreed's modified boot.c located here: https://github.com/jdah/tetris-os/issues/5#issuecomment-824512275

This allows it to boot in QEMU for me, albeit without any sound output.

**Comment by jdah** [comment]
You can now try by removing `#define ENABLE_MUSIC` in `main.c` which disables everything to do with sound/music/the SB16.

**Comment by marchellodev** [comment]
@jdah Yep, now it works!

**Comment by takaswie** [comment]
Hi,

I think the issue comes from QEMU's hardware emulation of ISA DMA and console device,
It seems not to be a bug of this pretty OS.

We can see several reports that QEMU's sb16 emulation causes some troubles:

 * OSDev.org • View topic - QEMU's (broken) support for Sound Blaster 16
   * https://forum.osdev.org/viewtopic.php?f=1&t=39652
 * QEMU official issue tracker
   * https://bugs.launchpad.net/qemu/?field.searchtext=sb16

In QEMU process, one thread handles console device and and ISA DMA transmission.
The combination seems to cause the issue. I guess screen reflesh is hard to occur
due to lock of handling IRQ in the thread.

As a workaround, I use any remote desktop protocol to suppress the freeze of display. Below
command-line is to start QEMU process with SPICE protocol support in unix domain socket:

```
$ qemu-system-i386 -drive format=raw,file=boot.iso -d cpu_reset \
  -accel kvm \
  -soundhw sb16 \
  -device virtio-serial-pci \
  -device virtserialport,chardev=spicechannel0,name=com.redhat.spice.0 \
  -chardev spicevmc,id=spicechannel0,name=vdagent \
  -spice unix,addr=/tmp/tetris.socket,disable-ticketing
```

Here, to avoid protocol overhead, unix domain is used.
Then connect to the socket by any SPICE viewer:

```
$ remote-viewer spice+unix:///tmp/tetris.socket
```


The remote-viewer is a part of libvirt project.
We can use the other protocol such as VNC.

Testing environment:

 * Ubuntu 20.10 (amd64)
 * AMD Ryzen 5 2400G with Radeon Vega Graphics
 * QEMU v5.0 (in ubuntu package version 1:5.0-5ubuntu9.7)
    * accelarated by KVM in Linux kernel v5.8

To prevent overrun of PCM buffer, below patch is applied:

```
$ git diff
diff --git a/src/sound.c b/src/sound.c
index cf567bf..e0c5738 100644
--- a/src/sound.c
+++ b/src/sound.c
@@ -148,7 +148,7 @@ static const f64 NOTES[NUM_OCTAVES * OCTAVE_SIZE] = {
 #define DSP_IRQ     0x80
 
 #define SAMPLE_RATE     48000
-#define BUFFER_MS       30
+#define BUFFER_MS       200
 
 #define BUFFER_SIZE ((size_t) (SAMPLE_RATE * (BUFFER_MS / 1000.0)))
 static i16 buffer[BUFFER_SIZE];
```


Cheers.

**Comment by jdah** [comment]
Thanks for the investigation @takaswie ! I think the best we can do on `BUFFER_MS` is actually 40 unfortunately, since  the buffer filling code is only run every `BUFFER_MS / 2`, so at larger values (especially 200) it isn't run frequently enough for some of the sixteenth notes in the music (at least at the preset 150 BPM for the theme) :) I'll link to this issue in the README and update `BUFFER_MS` to be 40.

**Comment by jdah** [comment]
I've linked your workaround into the README in dd21ffd7420dd692f38c35f34686c5a9f9fd107e @takaswie

**Comment by jdah** [comment]
Closing this issue since it's working now for @marchellodev. Thanks for the help everyone :)

**Comment by takaswie** [comment]
Hi @jdah,

Thanks for your clarification about buffer duration. Indeed, when running with remove desktop protocol, 40 (and original 30) msec is enough to play smooth sound.

I encounter the overrun issue just in the case of direct I/O from qemu process. I suspect further QEMU hardware emulation for ISA-related functions. If avoiding communication load, it might be worth to drop sound support since ISA is really old bus and few developer can maintain it... (but I note that Intel HDA driver should be heavy and complicated since it should support wide variety of HDA codecs developed by several hardware vendors...)

Anyway, thanks for the lovely OS!

**Comment by tegiac97** [comment]
> 
> 
> Hi,
> 
> I think the issue comes from QEMU's hardware emulation of ISA DMA and console device,
> It seems not to be a bug of this pretty OS.
> 
> We can see several reports that QEMU's sb16 emulation causes some troubles:
> 
>     * OSDev.org • View topic - QEMU's (broken) support for Sound Blaster 16
>       
>       * https://forum.osdev.org/viewtopic.php?f=1&t=39652
> 
>     * QEMU official issue tracker
>       
>       * https://bugs.launchpad.net/qemu/?field.searchtext=sb16
> 
> 
> In QEMU process, one thread handles console device and and ISA DMA transmission.
> The combination seems to cause the issue. I guess screen reflesh is hard to occur
> due to lock of handling IRQ in the thread.
> 
> As a workaround, I use any remote desktop protocol to suppress the freeze of display. Below
> command-line is to start QEMU process with SPICE protocol support in unix domain socket:
> 
> ```
> $ qemu-system-i386 -drive format=raw,file=boot.iso -d cpu_reset \
>   -accel kvm \
>   -soundhw sb16 \
>   -device virtio-serial-pci \
>   -device virtserialport,chardev=spicechannel0,name=com.redhat.spice.0 \
>   -chardev spicevmc,id=spicechannel0,name=vdagent \
>   -spice unix,addr=/tmp/tetris.socket,disable-ticketing
> ```
> 
> Here, to avoid protocol overhead, unix domain is used.
> Then connect to the socket by any SPICE viewer:
> 
> ```
> $ remote-viewer spice+unix:///tmp/tetris.socket
> ```
> 
> The remote-viewer is a part of libvirt project.
> We can use the other protocol such as VNC.
> 
> Testing environment:
> 
>     * Ubuntu 20.10 (amd64)
> 
>     * AMD Ryzen 5 2400G with Radeon Vega Graphics
> 
>     * QEMU v5.0 (in ubuntu package version 1:5.0-5ubuntu9.7)
>       
>       * accelarated by KVM in Linux kernel v5.8
> 
> 
> To prevent overrun of PCM buffer, below patch is applied:
> 
> ```
> $ git diff
> diff --git a/src/sound.c b/src/sound.c
> index cf567bf..e0c5738 100644
> --- a/src/sound.c
> +++ b/src/sound.c
> @@ -148,7 +148,7 @@ static const f64 NOTES[NUM_OCTAVES * OCTAVE_SIZE] = {
>  #define DSP_IRQ     0x80
>  
>  #define SAMPLE_RATE     48000
> -#define BUFFER_MS       30
> +#define BUFFER_MS       200
>  
>  #define BUFFER_SIZE ((size_t) (SAMPLE_RATE * (BUFFER_MS / 1000.0)))
>  static i16 buffer[BUFFER_SIZE];
> ```
> 
> Cheers.

This method work with WSL2. You must install GWSL or update to newest WSL and Windows Insider to show GUI.

**Comment by Drarig29** [comment]
To install the remote-viewer:

```sh
sudo apt install virt-viewer
```

**Comment by Drarig29** [comment]
I tried with Windows Insider and the new WSLg architecture and it does work!

However I can't make the audio work... Yet the sound works with VLC, so I think pulse audio should be working.

I get these errors:
```
(remote-viewer:20397): GSpice-WARNING **: 14:07:52.578: PulseAudio context failed Connection refused
(remote-viewer:20397): GSpice-WARNING **: 14:07:52.578: pa_context_connect() failed: Connection refused
```

**Comment by baryluk** [comment]
Hi. I just was testing. And even with the workaround, I am getting poor quality of audio, with default `BUFFER_MS` (40). With BUFFER_MS 200 it works.

I am using qemu 5.2 on Debian testing amd64, and run qemu with kvm.

My qemu doesn't like the `-audiodev pulseaudio,...`  , I also tried, sdl and it kind of works, but qemu says it is unknown audio driver, and the game freezes.  The virt-viewer method works.

If I just use `-device sb16`, it almost works, but even with BUFFER_MS 200, there are some interruptions (but it sounds way better than BUFFER_MS 40). However, no image shows up, beyond the initial `TETRIS TIME`.

It looks like the `virt-viewer` is only way for some reasons.

I am pretty sure this is fixable in tetris os tho, because I remember running DOS and sb16, in qemu few months ago (I modified mpg123 to implement sb16 driver).
